name: Build Kivy APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git zip unzip openjdk-17-jdk python3-pip \
            libncurses5 libffi-dev libssl-dev libsqlite3-dev libjpeg-dev libpng-dev \
            libgl1-mesa-dev libgles2-mesa-dev libgstreamer1.0 libmtdev-dev libgtk-3-dev \
            autoconf automake libtool pkg-config zlib1g-dev
          pip install --upgrade pip setuptools wheel cython
          pip install buildozer

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload generated APK
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: bin/*.apk
