name: Build Kivy Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt update

          # Fix unmet dependencies
          sudo apt install -y libunwind-dev

          # Install remaining dependencies
          sudo apt install -y build-essential ccache \
            libffi-dev libssl-dev libsqlite3-dev libjpeg-dev zlib1g-dev \
            libpng-dev python3-pip python3-setuptools zip unzip openjdk-17-jdk \
            git python3 python3-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
            libfreetype6-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            libmtdev-dev libncurses-dev

      - name: Install Buildozer and cython
        run: |
          pip install --upgrade pip
          pip install buildozer
          pip install cython

      - name: Initialize and build APK
        run: |
          buildozer android debug --verbose
