name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python and install Buildozer dependencies
      - name: Set up environment and install Buildozer
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git zip unzip openjdk-17-jdk libncurses5 libstdc++6 libffi-dev libssl-dev libsqlite3-dev zlib1g-dev libpng-dev libjpeg-dev libfreetype6-dev
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      # 3. Build the APK using Buildozer
      - name: Build APK
        run: |
          cd First_App
          buildozer android debug

      # 4. Show contents of the bin folder for debugging
      - name: Show APK files
        run: ls -R First_App/bin

      # 5. Upload the APK as an artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: First_App/bin/*.apk

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: downloaded-artifact

      - name: List downloaded files
        run: ls -R downloaded-artifact

      - name: Use the artifact
        run: echo "The artifact is in downloaded-artifact/"
