name: Build Kivy Calculator APK

on:  # Trigger workflows on push or pull request to main push: branches: - main pull_request: branches: - main

jobs: build: runs-on: ubuntu-latest strategy: matrix: python-version: [3.8, 3.10]

steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: ${{ matrix.python-version }}

  - name: Install system dependencies
    run: |
      sudo apt-get update || true
      sudo apt-get install -y python3-dev git build-essential libssl-dev libffi-dev

  - name: Install Python dependencies
    run: |
      python -m pip install --upgrade pip
      pip install buildozer kivy

  - name: Initialize Buildozer spec
    run: |
      if [ ! -f buildozer.spec ]; then buildozer init; fi
      # If you maintain a custom spec in the repo, override
      if [ -f .github/buildozer.spec ]; then cp .github/buildozer.spec buildozer.spec; fi

  - name: Build Android APK
    run: |
      buildozer android debug

  - name: Upload APK artifact
    uses: actions/upload-artifact@v3
    with:
      name: calculator-apk
      path: bin/*.apk

