name: Build Kivy Calculator APK

on: push: branches: [ main ] pull_request: branches: [ main ]

jobs: build: runs-on: ubuntu-latest

steps:
- name: Checkout repository
  uses: actions/checkout@v3

- name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.10'

- name: Install dependencies
  run: |
    sudo apt-get update
    sudo apt-get install -y python3-pip build-essential git python3-dev
    python -m pip install --upgrade pip
    pip install buildozer kivy

- name: Initialize Buildozer
  run: |
    buildozer init
    # Copy your pre-configured buildozer.spec if included in the repo
    if [ -f ./buildozer.spec ]; then mv buildozer.spec buildozer.spec.bak; fi
    cp .github/buildozer.spec ./buildozer.spec

- name: Build APK
  run: |
    buildozer android debug

- name: Upload APK artifact
  uses: actions/upload-artifact@v3
  with:
    name: calculator-apk
    path: bin/*.apk

