name: Build Kivy Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libunwind-dev autoconf automake libtool build-essential ccache \
            libffi-dev libssl-dev libsqlite3-dev libjpeg-dev zlib1g-dev libpng-dev \
            python3-pip python3-setuptools zip unzip git python3 python3-dev openjdk-17-jdk \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev \
            libswscale-dev libavformat-dev libavcodec-dev libfreetype6-dev \
            libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libmtdev-dev libncurses-dev pkg-config
      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install buildozer==1.5.0 cython
      - name: Download Android Command Line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
      
      - name: Install Android SDK and Build Tools
        run: |
          sdkmanager --sdk_root=$HOME/android-sdk --install "platform-tools" "platforms;android-33" "build-tools;34.0.0"
      - name: Verify AIDL Installation
        run: |
          if [ ! -f "$HOME/android-sdk/build-tools/34.0.0/aidl" ]; then
            echo "AIDL tool is not installed. Exiting."
            exit 1
          else
            echo "AIDL tool is successfully installed."
          fi
      - name: Fix SDK Permissions
        run: sudo chmod -R 777 $HOME/android-sdk

      - name: Build APK
        run: |
          buildozer android debug --verbose
