name: Build Kivy Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt update
          sudo apt install -y libunwind-dev autoconf automake libtool build-essential ccache \
            libffi-dev libssl-dev libsqlite3-dev libjpeg-dev zlib1g-dev libpng-dev \
            python3-pip python3-setuptools zip unzip openjdk-8-jdk git python3 python3-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev \
            libswscale-dev libavformat-dev libavcodec-dev libfreetype6-dev \
            libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libmtdev-dev libncurses-dev pkg-config

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install buildozer==1.5.0
          pip install cython

      - name: Ensure buildozer.spec exists
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Install Android cmdline-tools and update environment
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest
        env:
          ANDROID_SDK_ROOT: $HOME/android-sdk

      - name: Set up environment variables
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Install Android command-line tools and accept licenses
        run: |
          mkdir -p ~/.android && touch ~/.android/repositories.cfg
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/android
          rm -rf $ANDROID_HOME/cmdline-tools/latest
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          mv $HOME/android/cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_HOME} --licenses
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_HOME} "build-tools;36.0.0" "platforms;android-34"

      - name: Build APK
        run: |
          buildozer android debug --verbose
          if [ $? -ne 0 ]; then
            echo "Build failed. Check logs for details."
            exit 1
          fi
