name: Build Kivy APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies for Buildozer
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            ccache \
            git \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            libncurses5 \
            libjpeg-dev \
            libpng-dev \
            libgl1-mesa-dev \
            openjdk-17-jdk \
            unzip \
            zip \
            autoconf \
            libtool \
            pkg-config

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install Cython==0.29.36
          pip install buildozer

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload generated APK
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: bin/*.apk
