name: Build and Package Kivy APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        target-arch: ['armeabi-v7a', 'arm64-v8a'] # Add 'x86', 'x86_64' if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # If you have a requirements.txt file
        pip install kivy==2.2.1 # Or your desired Kivy version
        pip install buildozer

    - name: Update Buildozer Configuration
      run: |
        sed -i "s/# (title = MyApp)/title = ${{ github.event.repository.name }}/g" buildozer.spec
        sed -i "s/# (package.name = myapp)/package.name = ${{ github.event.repository.name | lower }}/g" buildozer.spec
        sed -i "s/# (package.domain = org.example)/package.domain = org.github.${{ github.event.repository.owner.login }}/g" buildozer.spec
        sed -i "s/# (source.include_exts = py,png,jpg,jpeg,gif,kv,atlas)/source.include_exts = py,png,jpg,jpeg,gif,kv,atlas,txt,ini/g" buildozer.spec # Add any other file extensions your app uses
        # Add any other buildozer configurations you need here
        # Example:
        # sed -i "s/# android.permissions = INTERNET/android.permissions = INTERNET/g" buildozer.spec

    - name: Build APK for ${{ matrix.target-arch }}
      run: |
        buildozer android_release --arch ${{ matrix.target-arch }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ matrix.target-arch }}
        path: bin/*.apk
        
